### ISSUE TITLE
1.4 Revisión de preguntas de 1.1

### ISSUE THREAD

**Issue by ondoheer** [Via-Codigo/curricula2018#5]
@drneox ya terminé las preguntas para 1.1, [revísalas](https://docs.google.com/document/d/1FVWHiVVUg3xv8d5eTSriLQwoBpwNkja3o610THEqrDw/edit) porfa, si te parcen, cierra el issue

**Comment by ondoheer** [comment]
Consolido la revisión en un solo issue

**Comment by drneox** [comment]
agregué un par más, me dices que te parecen .
